name: Fetch Wecima RSS

permissions:
  contents: write   # السماح للـ Actions بالكتابة على الريبو

on:
  schedule:
    - cron: '0 */6 * * *'   # كل 6 ساعات
  workflow_dispatch: {}      # تشغيل يدوي من Actions

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install puppeteer xml2js

      - name: Run fetch script
        run: node fetch_rss.js > movies.json

      - name: Commit movies.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add movies.json
          git commit -m "Update movies.json" || echo "No changes"
          git push
